name: Build iOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app

      - name: Build unsigned IPA
        run: |
          chmod +x ./build_unsigned_ipa.sh
          ./build_unsigned_ipa.sh

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReadApp
          path: build/ReadApp_unsigned.ipa
